version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: stock-exchange-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock_exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: javazerozahar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: stock-exchange-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: