version: '3.9'
services:
  app:
    build: .
    container_name: stock-exchange-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stock_exchange_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: javazerozahar
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: stock-exchange-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock_exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: javazerozahar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: stock-exchange-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge